name: stylish
description: A scalable Flutter eCommerce application built with MVVM architecture, responsive UI, localization support, and clean design system principles.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter_skill: ^0.2.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9

  # Navigation
  go_router: ^17.2.3

  # Networking
  internet_connection_checker_plus: ^3.0.0
  dio: ^5.9.2

  # State Management
  fpdart: ^1.2.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1

  # Backend – Firebase

  # Backend – Supabase

  # Backend – Appwrite

  # Storage
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.2.0

  # Images & SVG
  cached_network_image: ^3.4.1
  flutter_svg: ^2.3.0

  # Icons
  iconsax_plus: ^1.0.0

  # Shimmer / Skeleton
  skeletonizer: ^2.1.3

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Animations
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^2.0.1

  # Environment

  # Logging
  logger: ^2.7.0

  # Media
  image_picker: ^1.2.2

  # Utilities
  crypto: ^3.0.7
  connectivity_plus: ^7.1.1
  google_fonts: ^8.1.0

  # Device & System


  # Localization
  easy_localization: ^3.0.8

  flutter_native_splash: ^2.4.7
  get_it: ^9.2.1
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

